steps:
  - task: CopyFiles@2
    displayName: "Copy package.json to dist"
    inputs:
      SourceFolder: "$(System.DefaultWorkingDirectory)"
      Contents: "package.json"
      TargetFolder: "$(System.DefaultWorkingDirectory)/dist"

  - task: CopyFiles@2
    displayName: "Copy yarn.lock to dist"
    inputs:
      SourceFolder: "$(System.DefaultWorkingDirectory)"
      Contents: "yarn.lock"
      TargetFolder: "$(System.DefaultWorkingDirectory)/dist"


  - task: CopyFiles@2
    displayName: 'Copy prisma folder to dist'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/prisma'
      Contents: '**'
      TargetFolder: '$(System.DefaultWorkingDirectory)/dist/prisma'


  - task: AzureKeyVault@2
    inputs:
      azureSubscription: '$(azureServiceConnection)'
      KeyVaultName: '$(keyVaultName)'
      SecretsFilter: 'database-url'
      RunAsPreJob: false

  - script: 'yarn db:generate'
    displayName: Run DB generation
    env:
      # Read from key vault in task above
      DATABASE_URL: '$(database-url)'

  - script: 'yarn db:migrate-reset'
    displayName: Run DB migrations
    env:
      # Read from key vault in task above
      DATABASE_URL: '$(database-url)'

  - script: 'yarn db:seed'
    displayName: Run DB seed in dev and QA
    condition: or(eq(variables.azureServiceConnection, 'qa'), eq(variables.azureServiceConnection, 'dev'))
    env:
      #  Retrieved from key vault in task above
      DATABASE_URL: '$(database-url)'

  - task: AzureRmWebAppDeployment@4
    displayName: "Deploy app"
    inputs:
      ConnectionType: "AzureRM"
      azureSubscription: "$(azureServiceConnection)"
      appType: "webAppLinux"
      WebAppName: "$(webAppName)"
      packageForLinux: "$(System.DefaultWorkingDirectory)/dist"
      runtimeStack: "NODE|16-lts"
      StartupCommand: "yarn install --production=true --network-timeout 3600000 && node src/main"
      AppSettings: "-WEBSITES_CONTAINER_START_TIME_LIMIT 1800
      -DATABASE_URL @Microsoft.KeyVault(VaultName=$(keyVaultName);SecretName=database-url)
      -SENDGRID_API_KEY @Microsoft.KeyVault(VaultName=$(keyVaultName);SecretName=sendgrid-api)
      -APPLICATIONINSIGHTS_CONNECTION_STRING @Microsoft.KeyVault(VaultName=$(keyVaultName);SecretName=applicationinsights-connection-string)
      -JWT_SECRET @Microsoft.KeyVault(VaultName=$(keyVaultName);SecretName=jwt-secret)
      -STRIPE_API_KEY @Microsoft.KeyVault(VaultName=$(keyVaultName);SecretName=stripe-key)
      -STRIPE_API_SECRET @Microsoft.KeyVault(VaultName=$(keyVaultName);SecretName=stripe-secret)
      -ApplicationInsightsAgent_EXTENSION_VERSION ~3
      -STORAGE_ACCOUNT_CONNECTION_STRING @Microsoft.KeyVault(VaultName=$(keyVaultName);SecretName=storage-account-connection-string)"