trigger:
  - dev

pool:
  vmImage: "ubuntu-22.04"

variables:
  azureServiceConnection: "dev"
  webAppName: "DesksidesApiDev"
  keyVaultName: "DesksidesKeyVaultDevRed"

steps:
  - template: ./build.yaml
  - template: ./deploy.yaml
