trigger:
  - main

pool:
  vmImage: "ubuntu-22.04"

variables:
  azureServiceConnection: "prod"
  webAppName: "DesksidesApi"
  keyVaultName: "DesksidesKeyVaultBlue"

steps:
  - template: ./build.yaml
  - template: ./deploy.yaml
