export const publications = [
  { label: 'Vogue' },
  { label: 'Architectural Digest' },
  { label: 'Allure' },
  { label: 'Bon Appetit' },
  { label: 'Conde Nast Traveler' },
  { label: 'Epicurious' },
  { label: 'Glamour' },
  { label: 'GQ' },
  { label: 'SELF' },
  { label: 'Tatler' },
  { label: 'Teen Vogue' },
  { label: 'The New Yorker' },
  { label: 'Vanity Fair' },
  { label: 'Cosmopolitan' },
  { label: 'Country Living' },
  { label: 'Delish' },
  { label: 'ELLE' },
  { label: 'ELLE Decor' },
  { label: 'Esquire' },
  { label: 'Food Network Magazine' },
  { label: 'Good Housekeeping' },
  { label: 'Harper’s Bazaar' },
  { label: 'HGTV Magazine' },
  { label: 'House Beautiful' },
  { label: 'Men’s Health' },
  { label: 'Oprah Daily' },
  { label: 'Prevention' },
  { label: 'Redbook' },
  { label: 'Runner’s World' },
  { label: 'Seventeen' },
  { label: 'Town & Country' },
  { label: 'Veranda' },
  { label: 'Woman’s Day' },
  { label: 'Women’s Health' },
  { label: 'VeryWell' },
  { label: 'Health' },
  { label: 'Parents' },
  { label: 'All Recipes' },
  { label: 'The Spruce Eats' },
  { label: 'EatingWell' },
  { label: 'Food & Wine' },
  { label: 'Better Homes & Gardens' },
  { label: 'Martha Stewart Living' },
  { label: 'The Spruce' },
  { label: 'Real Simple' },
  { label: 'MyDomaine' },
  { label: 'Domino' },
  { label: 'Southern Living' },
  { label: 'Byrdie' },
  { label: 'Bustle' },
  { label: 'Popsugar' },
  { label: 'Purewow' },
  { label: 'InStyle' },
  { label: 'Shape' },
  { label: 'Travel + Leisure' },
  { label: 'Treehugger' },
  { label: 'People' },
  { label: 'Coastal Living' },
  { label: 'Traditional Home' },
];

export const industries = [
  { label: 'Fashion' },
  { label: 'Beauty' },
  { label: 'Domestic Lifestyle' },
  { label: 'Health and Wellness' },
  { label: 'Travel' },
  { label: 'Tech' },
  { label: 'Parenting' },
  { label: 'Food and Beverage' },
  { label: 'Interior Design and Architecture' },
  { label: 'Entertainment and Culture' },
  { label: 'Fitness' },
  { label: 'Business' },
  { label: 'Sustainability' },
  { label: 'Sports' },
  { label: 'Consumer Goods' },
];
